### ISSUE TITLE
Integrate Roassal stacked visualizations into the Results tab

### ISSUE THREAD

**Issue by hernanmd** [rakki-18/Matrix-Benchmarks#11]
The Results tab has much space available which could be used by adding another presenter for the Roassal canvas. This canvas would include the stacked histograms from the results of the last executions.

**Comment by rakki-18** [comment]
@hernanmd Can you please check once now?

**Comment by hernanmd** [comment]
Seems nice!! Thank you. A minor suggestion is that once the results are ready it would be more interesting to switch to the Plots tab, and to avoid the additional Roassal window which is still opened.

**Comment by rakki-18** [comment]
Yes

> Seems nice!! Thank you. A minor suggestion is that once the results are ready it would be more interesting to switch to the Plots tab, and to avoid the additional Roassal window which is still opened.

Yeah, that would be better. 
But currently, a Roassal window is being opened because in the backend of the Spec application, I am running `runBenchmarks`, which opens up the new window.
If the user were to execute `runBenchmarks` programmatically without using the GUI, we would want to display a Roassal window which can't be avoided.
So, I came up with this work-around.
